"""HTTP routes for the execution and risk-control boot service."""

from __future__ import annotations

from fastapi import APIRouter, HTTPException

from boots.execution_boot.services.execution_service import get_execution_service
from infrastructure.schemas import (
    RiskCheckRequest,
    RiskCheckResponse,
    PipelineStatusResponse,
    TradeOrderRequest,
    TradeOrderResponse,
)


router = APIRouter(prefix="/api/v1/execution", tags=["execution"])


@router.post("/risk-check", response_model=RiskCheckResponse)
def risk_check(request: RiskCheckRequest) -> RiskCheckResponse:
    """Evaluate a synchronous risk-check request.

    Args:
        request: Risk evaluation payload submitted by the caller.

    Returns:
        Risk approval result generated by the execution service.
    """

    service = get_execution_service()
    return service.risk_check(request)


@router.post("/trade-orders", response_model=TradeOrderResponse)
def create_trade_order(request: TradeOrderRequest) -> TradeOrderResponse:
    """Create a synthetic trade order after explicit approval.

    Args:
        request: Order creation payload submitted by the caller.

    Returns:
        Generated trade-order response.

    Raises:
        HTTPException: Raised when the request has not been approved yet.
    """

    service = get_execution_service()
    if not request.approved:
        raise HTTPException(status_code=400, detail="Order cannot be created before risk approval")
    return service.create_trade_order(request)


@router.get("/pipeline-status", response_model=PipelineStatusResponse)
def get_pipeline_status() -> PipelineStatusResponse:
    """Expose the latest event state seen by the execution boot service."""

    service = get_execution_service()
    return service.get_pipeline_status()